/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_durongze_jni_CallC */

#ifndef _Included_com_durongze_jni_CallC
#define _Included_com_durongze_jni_CallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_durongze_jni_CallC
 * Method:    CInterface
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_durongze_jni_CallC_CInterface
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
