/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_durongze_jni_CallC */

#ifndef _Included_com_durongze_jni_CallC
#define _Included_com_durongze_jni_CallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_durongze_jni_CallC
 * Method:    CInterface
 * Signature: ([Ljava/lang/String;[I[FI)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_durongze_jni_CallC_CInterface
  (JNIEnv *, jobject, jobjectArray, jintArray, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
